---
- name: install springpetclinic on ubuntu
  become: yes
  hosts: all
  tasks:
    - name: install java on ubuntu
      ansible.builtin.apt:
        name: openjdk-17-jdk
        update_cache: true
        state: present
    - name: install maven on ubuntu
      ansible.builtin.apt:
        name: maven
        state: present
        update_cache: true
    - name: git clone spring-pet-clinic
      ansible.builtin.get_url:
        url: https://github.com/hemachaitanya/spring-petclinic.git
        dest: /tmp
    - name: copy service file to systemd
      command: /tmp/spring-petclinic/target/ ls
    - name: maven version
      ansible.builtin.package:
        name: mvn
        state: present