# this is tomcat
- name: inatall tomcat10 on ubuntu
  hosts: all
  become: yes
  tasks: 
    - name: install java
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: true
        state: present
    - name: create user tomcat10
      ansible.builtin.user:
        create_home: true
        group: tomcat
        name: tomcat
        home: /opt/tomcat
        shell: /bin/false
        state: present
    - name: create group
      ansible.builtin.group:
        name: tomcat
        state: present
    - name: extract tomcat
      ansible.builtin.unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
        remote_src: yes
        dest: tar.gz -C /opt/tomcat
    - name: create a symbolic link
      ansible.builtin.file:
        src: /opt/tomcat/apache-tomcat-10.0.20
        dest: /opt/tomcat/latest
        state: link
    - name: change permissions
      ansible.builtin.file:
        dest: /opt/tomcat
        recurse: true
        owner: tomcat
        group: tomcat
        state: directory
    - name: add execute peermissons to shell file
      ansible.builtin.command:
        chdir: 'chmod +x /opt/tomcat/latest/bin/*.sh'
    - name: create a systemd unitfile
      ansible.builtin.copy:
        src: tomcat.service
        dest: /etc/systemd/system/tomcat.service
        owner: tomcat
        group: tomcat
    - name: reload demon and start tomcat
      ansible.builtin.systemd:
        name: systemctl demon and start tomcat
        demond_reload: yes
        enable: yes
        state: restarted
    